/*
Jellyfin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 10.8.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the SessionInfoFullNowPlayingItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionInfoFullNowPlayingItem{}

// SessionInfoFullNowPlayingItem Class BaseItem.
type SessionInfoFullNowPlayingItem struct {
	Size NullableInt64 `json:"Size,omitempty"`
	Container NullableString `json:"Container,omitempty"`
	IsHD *bool `json:"IsHD,omitempty"`
	IsShortcut *bool `json:"IsShortcut,omitempty"`
	ShortcutPath NullableString `json:"ShortcutPath,omitempty"`
	Width *int32 `json:"Width,omitempty"`
	Height *int32 `json:"Height,omitempty"`
	ExtraIds []string `json:"ExtraIds,omitempty"`
	DateLastSaved *time.Time `json:"DateLastSaved,omitempty"`
	// Gets or sets the remote trailers.
	RemoteTrailers []MediaUrl `json:"RemoteTrailers,omitempty"`
	SupportsExternalTransfer *bool `json:"SupportsExternalTransfer,omitempty"`
}

// NewSessionInfoFullNowPlayingItem instantiates a new SessionInfoFullNowPlayingItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionInfoFullNowPlayingItem() *SessionInfoFullNowPlayingItem {
	this := SessionInfoFullNowPlayingItem{}
	return &this
}

// NewSessionInfoFullNowPlayingItemWithDefaults instantiates a new SessionInfoFullNowPlayingItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionInfoFullNowPlayingItemWithDefaults() *SessionInfoFullNowPlayingItem {
	this := SessionInfoFullNowPlayingItem{}
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionInfoFullNowPlayingItem) GetSize() int64 {
	if o == nil || IsNil(o.Size.Get()) {
		var ret int64
		return ret
	}
	return *o.Size.Get()
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionInfoFullNowPlayingItem) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Size.Get(), o.Size.IsSet()
}

// HasSize returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasSize() bool {
	if o != nil && o.Size.IsSet() {
		return true
	}

	return false
}

// SetSize gets a reference to the given NullableInt64 and assigns it to the Size field.
func (o *SessionInfoFullNowPlayingItem) SetSize(v int64) {
	o.Size.Set(&v)
}
// SetSizeNil sets the value for Size to be an explicit nil
func (o *SessionInfoFullNowPlayingItem) SetSizeNil() {
	o.Size.Set(nil)
}

// UnsetSize ensures that no value is present for Size, not even an explicit nil
func (o *SessionInfoFullNowPlayingItem) UnsetSize() {
	o.Size.Unset()
}

// GetContainer returns the Container field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionInfoFullNowPlayingItem) GetContainer() string {
	if o == nil || IsNil(o.Container.Get()) {
		var ret string
		return ret
	}
	return *o.Container.Get()
}

// GetContainerOk returns a tuple with the Container field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionInfoFullNowPlayingItem) GetContainerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Container.Get(), o.Container.IsSet()
}

// HasContainer returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasContainer() bool {
	if o != nil && o.Container.IsSet() {
		return true
	}

	return false
}

// SetContainer gets a reference to the given NullableString and assigns it to the Container field.
func (o *SessionInfoFullNowPlayingItem) SetContainer(v string) {
	o.Container.Set(&v)
}
// SetContainerNil sets the value for Container to be an explicit nil
func (o *SessionInfoFullNowPlayingItem) SetContainerNil() {
	o.Container.Set(nil)
}

// UnsetContainer ensures that no value is present for Container, not even an explicit nil
func (o *SessionInfoFullNowPlayingItem) UnsetContainer() {
	o.Container.Unset()
}

// GetIsHD returns the IsHD field value if set, zero value otherwise.
func (o *SessionInfoFullNowPlayingItem) GetIsHD() bool {
	if o == nil || IsNil(o.IsHD) {
		var ret bool
		return ret
	}
	return *o.IsHD
}

// GetIsHDOk returns a tuple with the IsHD field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfoFullNowPlayingItem) GetIsHDOk() (*bool, bool) {
	if o == nil || IsNil(o.IsHD) {
		return nil, false
	}
	return o.IsHD, true
}

// HasIsHD returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasIsHD() bool {
	if o != nil && !IsNil(o.IsHD) {
		return true
	}

	return false
}

// SetIsHD gets a reference to the given bool and assigns it to the IsHD field.
func (o *SessionInfoFullNowPlayingItem) SetIsHD(v bool) {
	o.IsHD = &v
}

// GetIsShortcut returns the IsShortcut field value if set, zero value otherwise.
func (o *SessionInfoFullNowPlayingItem) GetIsShortcut() bool {
	if o == nil || IsNil(o.IsShortcut) {
		var ret bool
		return ret
	}
	return *o.IsShortcut
}

// GetIsShortcutOk returns a tuple with the IsShortcut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfoFullNowPlayingItem) GetIsShortcutOk() (*bool, bool) {
	if o == nil || IsNil(o.IsShortcut) {
		return nil, false
	}
	return o.IsShortcut, true
}

// HasIsShortcut returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasIsShortcut() bool {
	if o != nil && !IsNil(o.IsShortcut) {
		return true
	}

	return false
}

// SetIsShortcut gets a reference to the given bool and assigns it to the IsShortcut field.
func (o *SessionInfoFullNowPlayingItem) SetIsShortcut(v bool) {
	o.IsShortcut = &v
}

// GetShortcutPath returns the ShortcutPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionInfoFullNowPlayingItem) GetShortcutPath() string {
	if o == nil || IsNil(o.ShortcutPath.Get()) {
		var ret string
		return ret
	}
	return *o.ShortcutPath.Get()
}

// GetShortcutPathOk returns a tuple with the ShortcutPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionInfoFullNowPlayingItem) GetShortcutPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShortcutPath.Get(), o.ShortcutPath.IsSet()
}

// HasShortcutPath returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasShortcutPath() bool {
	if o != nil && o.ShortcutPath.IsSet() {
		return true
	}

	return false
}

// SetShortcutPath gets a reference to the given NullableString and assigns it to the ShortcutPath field.
func (o *SessionInfoFullNowPlayingItem) SetShortcutPath(v string) {
	o.ShortcutPath.Set(&v)
}
// SetShortcutPathNil sets the value for ShortcutPath to be an explicit nil
func (o *SessionInfoFullNowPlayingItem) SetShortcutPathNil() {
	o.ShortcutPath.Set(nil)
}

// UnsetShortcutPath ensures that no value is present for ShortcutPath, not even an explicit nil
func (o *SessionInfoFullNowPlayingItem) UnsetShortcutPath() {
	o.ShortcutPath.Unset()
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *SessionInfoFullNowPlayingItem) GetWidth() int32 {
	if o == nil || IsNil(o.Width) {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfoFullNowPlayingItem) GetWidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *SessionInfoFullNowPlayingItem) SetWidth(v int32) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *SessionInfoFullNowPlayingItem) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfoFullNowPlayingItem) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *SessionInfoFullNowPlayingItem) SetHeight(v int32) {
	o.Height = &v
}

// GetExtraIds returns the ExtraIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionInfoFullNowPlayingItem) GetExtraIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ExtraIds
}

// GetExtraIdsOk returns a tuple with the ExtraIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionInfoFullNowPlayingItem) GetExtraIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExtraIds) {
		return nil, false
	}
	return o.ExtraIds, true
}

// HasExtraIds returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasExtraIds() bool {
	if o != nil && !IsNil(o.ExtraIds) {
		return true
	}

	return false
}

// SetExtraIds gets a reference to the given []string and assigns it to the ExtraIds field.
func (o *SessionInfoFullNowPlayingItem) SetExtraIds(v []string) {
	o.ExtraIds = v
}

// GetDateLastSaved returns the DateLastSaved field value if set, zero value otherwise.
func (o *SessionInfoFullNowPlayingItem) GetDateLastSaved() time.Time {
	if o == nil || IsNil(o.DateLastSaved) {
		var ret time.Time
		return ret
	}
	return *o.DateLastSaved
}

// GetDateLastSavedOk returns a tuple with the DateLastSaved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfoFullNowPlayingItem) GetDateLastSavedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateLastSaved) {
		return nil, false
	}
	return o.DateLastSaved, true
}

// HasDateLastSaved returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasDateLastSaved() bool {
	if o != nil && !IsNil(o.DateLastSaved) {
		return true
	}

	return false
}

// SetDateLastSaved gets a reference to the given time.Time and assigns it to the DateLastSaved field.
func (o *SessionInfoFullNowPlayingItem) SetDateLastSaved(v time.Time) {
	o.DateLastSaved = &v
}

// GetRemoteTrailers returns the RemoteTrailers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionInfoFullNowPlayingItem) GetRemoteTrailers() []MediaUrl {
	if o == nil {
		var ret []MediaUrl
		return ret
	}
	return o.RemoteTrailers
}

// GetRemoteTrailersOk returns a tuple with the RemoteTrailers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionInfoFullNowPlayingItem) GetRemoteTrailersOk() ([]MediaUrl, bool) {
	if o == nil || IsNil(o.RemoteTrailers) {
		return nil, false
	}
	return o.RemoteTrailers, true
}

// HasRemoteTrailers returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasRemoteTrailers() bool {
	if o != nil && !IsNil(o.RemoteTrailers) {
		return true
	}

	return false
}

// SetRemoteTrailers gets a reference to the given []MediaUrl and assigns it to the RemoteTrailers field.
func (o *SessionInfoFullNowPlayingItem) SetRemoteTrailers(v []MediaUrl) {
	o.RemoteTrailers = v
}

// GetSupportsExternalTransfer returns the SupportsExternalTransfer field value if set, zero value otherwise.
func (o *SessionInfoFullNowPlayingItem) GetSupportsExternalTransfer() bool {
	if o == nil || IsNil(o.SupportsExternalTransfer) {
		var ret bool
		return ret
	}
	return *o.SupportsExternalTransfer
}

// GetSupportsExternalTransferOk returns a tuple with the SupportsExternalTransfer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfoFullNowPlayingItem) GetSupportsExternalTransferOk() (*bool, bool) {
	if o == nil || IsNil(o.SupportsExternalTransfer) {
		return nil, false
	}
	return o.SupportsExternalTransfer, true
}

// HasSupportsExternalTransfer returns a boolean if a field has been set.
func (o *SessionInfoFullNowPlayingItem) HasSupportsExternalTransfer() bool {
	if o != nil && !IsNil(o.SupportsExternalTransfer) {
		return true
	}

	return false
}

// SetSupportsExternalTransfer gets a reference to the given bool and assigns it to the SupportsExternalTransfer field.
func (o *SessionInfoFullNowPlayingItem) SetSupportsExternalTransfer(v bool) {
	o.SupportsExternalTransfer = &v
}

func (o SessionInfoFullNowPlayingItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionInfoFullNowPlayingItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Size.IsSet() {
		toSerialize["Size"] = o.Size.Get()
	}
	if o.Container.IsSet() {
		toSerialize["Container"] = o.Container.Get()
	}
	if !IsNil(o.IsHD) {
		toSerialize["IsHD"] = o.IsHD
	}
	if !IsNil(o.IsShortcut) {
		toSerialize["IsShortcut"] = o.IsShortcut
	}
	if o.ShortcutPath.IsSet() {
		toSerialize["ShortcutPath"] = o.ShortcutPath.Get()
	}
	if !IsNil(o.Width) {
		toSerialize["Width"] = o.Width
	}
	if !IsNil(o.Height) {
		toSerialize["Height"] = o.Height
	}
	if o.ExtraIds != nil {
		toSerialize["ExtraIds"] = o.ExtraIds
	}
	if !IsNil(o.DateLastSaved) {
		toSerialize["DateLastSaved"] = o.DateLastSaved
	}
	if o.RemoteTrailers != nil {
		toSerialize["RemoteTrailers"] = o.RemoteTrailers
	}
	if !IsNil(o.SupportsExternalTransfer) {
		toSerialize["SupportsExternalTransfer"] = o.SupportsExternalTransfer
	}
	return toSerialize, nil
}

type NullableSessionInfoFullNowPlayingItem struct {
	value *SessionInfoFullNowPlayingItem
	isSet bool
}

func (v NullableSessionInfoFullNowPlayingItem) Get() *SessionInfoFullNowPlayingItem {
	return v.value
}

func (v *NullableSessionInfoFullNowPlayingItem) Set(val *SessionInfoFullNowPlayingItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionInfoFullNowPlayingItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionInfoFullNowPlayingItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionInfoFullNowPlayingItem(val *SessionInfoFullNowPlayingItem) *NullableSessionInfoFullNowPlayingItem {
	return &NullableSessionInfoFullNowPlayingItem{value: val, isSet: true}
}

func (v NullableSessionInfoFullNowPlayingItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionInfoFullNowPlayingItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


