/*
Jellyfin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// HlsAudioSeekStrategy An enum representing the options to seek the input audio stream when transcoding HLS segments.
type HlsAudioSeekStrategy string

// List of HlsAudioSeekStrategy
const (
	HLSAUDIOSEEKSTRATEGY_TRIM_COPIED_AUDIO HlsAudioSeekStrategy = "TrimCopiedAudio"
	HLSAUDIOSEEKSTRATEGY_TRANSCODE_AUDIO HlsAudioSeekStrategy = "TranscodeAudio"
)

// All allowed values of HlsAudioSeekStrategy enum
var AllowedHlsAudioSeekStrategyEnumValues = []HlsAudioSeekStrategy{
	"TrimCopiedAudio",
	"TranscodeAudio",
}

func (v *HlsAudioSeekStrategy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := HlsAudioSeekStrategy(value)
	for _, existing := range AllowedHlsAudioSeekStrategyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid HlsAudioSeekStrategy", value)
}

// NewHlsAudioSeekStrategyFromValue returns a pointer to a valid HlsAudioSeekStrategy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewHlsAudioSeekStrategyFromValue(v string) (*HlsAudioSeekStrategy, error) {
	ev := HlsAudioSeekStrategy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for HlsAudioSeekStrategy: valid values are %v", v, AllowedHlsAudioSeekStrategyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v HlsAudioSeekStrategy) IsValid() bool {
	for _, existing := range AllowedHlsAudioSeekStrategyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to HlsAudioSeekStrategy value
func (v HlsAudioSeekStrategy) Ptr() *HlsAudioSeekStrategy {
	return &v
}

type NullableHlsAudioSeekStrategy struct {
	value *HlsAudioSeekStrategy
	isSet bool
}

func (v NullableHlsAudioSeekStrategy) Get() *HlsAudioSeekStrategy {
	return v.value
}

func (v *NullableHlsAudioSeekStrategy) Set(val *HlsAudioSeekStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableHlsAudioSeekStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableHlsAudioSeekStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHlsAudioSeekStrategy(val *HlsAudioSeekStrategy) *NullableHlsAudioSeekStrategy {
	return &NullableHlsAudioSeekStrategy{value: val, isSet: true}
}

func (v NullableHlsAudioSeekStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHlsAudioSeekStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

