/*
Jellyfin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 10.8.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ObjectGroupUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectGroupUpdate{}

// ObjectGroupUpdate Class GroupUpdate.
type ObjectGroupUpdate struct {
	// Gets the group identifier.
	GroupId *string `json:"GroupId,omitempty"`
	// Gets the update type.
	Type *GroupUpdateType `json:"Type,omitempty"`
	// Gets the update data.
	Data interface{} `json:"Data,omitempty"`
}

// NewObjectGroupUpdate instantiates a new ObjectGroupUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectGroupUpdate() *ObjectGroupUpdate {
	this := ObjectGroupUpdate{}
	return &this
}

// NewObjectGroupUpdateWithDefaults instantiates a new ObjectGroupUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectGroupUpdateWithDefaults() *ObjectGroupUpdate {
	this := ObjectGroupUpdate{}
	return &this
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *ObjectGroupUpdate) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectGroupUpdate) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *ObjectGroupUpdate) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *ObjectGroupUpdate) SetGroupId(v string) {
	o.GroupId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ObjectGroupUpdate) GetType() GroupUpdateType {
	if o == nil || IsNil(o.Type) {
		var ret GroupUpdateType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectGroupUpdate) GetTypeOk() (*GroupUpdateType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ObjectGroupUpdate) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given GroupUpdateType and assigns it to the Type field.
func (o *ObjectGroupUpdate) SetType(v GroupUpdateType) {
	o.Type = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ObjectGroupUpdate) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ObjectGroupUpdate) GetDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ObjectGroupUpdate) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given interface{} and assigns it to the Data field.
func (o *ObjectGroupUpdate) SetData(v interface{}) {
	o.Data = v
}

func (o ObjectGroupUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectGroupUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupId) {
		toSerialize["GroupId"] = o.GroupId
	}
	if !IsNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	if o.Data != nil {
		toSerialize["Data"] = o.Data
	}
	return toSerialize, nil
}

type NullableObjectGroupUpdate struct {
	value *ObjectGroupUpdate
	isSet bool
}

func (v NullableObjectGroupUpdate) Get() *ObjectGroupUpdate {
	return v.value
}

func (v *NullableObjectGroupUpdate) Set(val *ObjectGroupUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectGroupUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectGroupUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectGroupUpdate(val *ObjectGroupUpdate) *NullableObjectGroupUpdate {
	return &NullableObjectGroupUpdate{value: val, isSet: true}
}

func (v NullableObjectGroupUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectGroupUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


